name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn -B test

  #Sonar's Job
  sonar:
    #Depends on test's job
    needs: tests
    name: SonarCloud analysis
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can  access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
        #Set up SonarCloud cache
      - name: Cache SonarCloud packages
        #This action allows caching dependencies and build outputs to improve  workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      #Set up Maven cache
      - name: Cache Maven packages
    #This action allows caching dependencies and build outputs to improve  workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        #Analyze project with SonarCloud
      - name: Analyze with SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=davidrotaborudea_labcicd -Dsonar.organization=davidrotaborudea -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:
    # Depende del job 'sonar'
    needs: sonar
    name: Build
    # Se ejecuta en la última versión de Ubuntu
    runs-on: ubuntu-latest

    steps:
      # ANTES DE EMPEZAR CON EL JAR HACE LO DE COVERALLS
      - uses: actions/checkout@v1

      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v1

      # 2. Configura JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # 3. Cachea los paquetes de Maven
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
# Paso 4: Compilar y ejecutar tests con Maven
      - name: Run Tests and Generate Coverage
        run: mvn clean test jacoco:report

# Paso 5: Verificar la estructura del directorio para asegurarse de que el reporte de Jacoco se ha generado
      - name: List target directory
        run: ls -R target

# Paso 6: Enviar el reporte de cobertura a Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: target/site/jacoco/jacoco.xml
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      # 4. Construye la aplicación usando Maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      # 5. Sube el JAR generado como un artefacto
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target/labcicd-0.0.1-SNAPSHOT.jar

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: davidrotaborudea/labcicd
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Cambia por la región que uses
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 8793-8127-2743.dkr.ecr.$AWS_REGION.amazonaws.com

          - name: Build Docker image
            run: docker build -t davidrotabor/labcicd:latest

          - name: Tag Docker image
            run: docker tag springboot-app:latest 8793-8127-2743.dkr.ecr.$AWS_REGION.amazonaws.com/davidrotabor/labcicd:latest

          - name: Push Docker image to ECR
            run: docker push 8793-8127-2743.dkr.ecr.$AWS_REGION.amazonaws.com/davidrotabor/labcicd:latest

